version: "3"
services:
  blog:
    command: jekyll serve --watch
    image: jekyll/jekyll:latest
    volumes:
      # - $PWD:/srv/jekyll
      # - $PWD/vendor/bundle:/usr/local/bundle
      - .:/srv/jekyll
    ports:
      - 4000:4000
      # - 45729:35729
      # - 6000:3000
      # - 80:4000
