version: "3"
services:
  site:
    command: jekyll build
    image: jekyll/jekyll:latest
    volumes:
      # - $PWD:/srv/jekyll
      # - $PWD/vendor/bundle:/usr/local/bundle
      - ./site:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      # - 45729:35729
      # - 6000:3000
      # - 80:4000
